import  "./global.scss"
import { Sora } from "next/font/google";

const sora = Sora({ 
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500'],
  style: ['normal']
});

export const metadata = {
  title: "ecommerce bike",
  description: "Generated by create Henrique Rigoni",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={sora.className}>
      <body>{children}</body>
    </html>
  );
}
